.simulate_hfsis_session <- function(seed, n = 390L, p = 25L) {
  set.seed(seed)
  delta <- 1 / n
  latent <- matrix(stats::rnorm(n * 6L), nrow = n)
  x <- matrix(stats::rnorm(n * p), nrow = n)
  x[, 1L] <- latent[, 1L]
  x[, 2L] <- 0.92 * latent[, 1L] + sqrt(1 - 0.92^2) * latent[, 2L]
  x[, 3L:5L] <- latent[, 3L:5L]
  for (j in 6L:p) {
    block <- 1L + ((j - 6L) %% 5L)
    x[, j] <- 0.65 * latent[, block] + sqrt(1 - 0.65^2) * x[, j]
  }
  x <- x * sqrt(delta)
  beta <- c(0.50, -0.52, 0.40, -0.35, 0.30, rep(0, p - 5L))
  local_scale <- 0.75 + 0.35 * sin(2 * pi * seq_len(n) / n)
  x <- x * local_scale
  y <- drop(x %*% beta) + 0.15 * sqrt(delta) * stats::rnorm(n)
  jump_rows <- c(83L, 318L, 370L)
  x[jump_rows, c(2L, 11L, 19L)] <- x[jump_rows, c(2L, 11L, 19L)] +
    c(0.09, -0.08, 0.11)
  y[jump_rows] <- y[jump_rows] + c(0.07, -0.10, 0.08)
  variable_names <- sprintf("x%02d", seq_len(p))
  data.frame(
    time_index = seq_len(n), y = y,
    stats::setNames(as.data.frame(x), variable_names),
    check.names = FALSE
  )
}

.make_hfsis_examples <- function(seed = 20260004L) {
  sessions <- lapply(seq_len(5L), function(index) {
    .simulate_hfsis_session(seed + index - 1L)
  })
  names(sessions) <- paste0("session_", seq_along(sessions))
  x_names <- sprintf("x%02d", seq_len(25L))
  metadata <- data.frame(
    variable = x_names,
    cluster = rep(paste0("cluster_", 1:5), each = 5L),
    active = x_names %in% x_names[1:5],
    stringsAsFactors = FALSE
  )
  list(
    hf_sis_example = list(
      data = sessions[[1L]],
      x_names = x_names,
      response = "y",
      target_index = 131L,
      windows = c(32L, 64L, 128L),
      true_support = x_names[1:5],
      description = paste(
        "Synthetic 390-increment session with five active coordinates,",
        "correlated blocks, coefficient cancellation, and finite-activity jumps."
      ),
      metadata = metadata
    ),
    hf_sis_panel_example = list(
      sessions = sessions,
      x_names = x_names,
      response = "y",
      target_index = 131L,
      windows = c(32L, 64L, 128L),
      true_support = x_names[1:5],
      description = "Five reproducible sessions from the HF-SIS synthetic design.",
      metadata = metadata
    )
  )
}

#' Synthetic high-frequency screening examples
#'
#' `hf_sis_example` is one 390-increment session with 25 covariates, correlated
#' blocks, coefficient cancellation, and a small number of jumps.
#' `hf_sis_panel_example` contains five sessions from the same design for
#' repeated-sample summaries. The true support is `x01` through `x05`.
#'
#' @format `hf_sis_example` is a list with components `data`, `x_names`,
#'   `response`, `target_index`, `windows`, `true_support`,
#'   `description`, and `metadata`. `hf_sis_panel_example` has the same
#'   metadata and a `sessions` list in place of `data`.
#' @source Generated by `data-raw/make-example-data.R` with fixed seed
#'   20260004; no proprietary or external data are included.
#' @references Zhu, H. *Ultra-high-dimensional spot support screening in
#'   continuous-time regression*. Manuscript.
#' @docType data
#' @keywords datasets
#' @usage data(hf_sis_example)
#'   data(hf_sis_panel_example)
#' @aliases hf_sis_example hf_sis_panel_example
#' @name hfsis_example_data
NULL
